-- DataFlow360 — Migration 007
-- F1.10 : entrepôt en étoile (schéma dwh) — Sprint 3, Aissata
--
-- Le contrat est docs/contrats/entrepot.md : tables, grains, clés, ligne
-- « inconnu » de chaque dimension. Une seule migration, car les sept objets
-- sont interdépendants (clés étrangères) dès leur création.
--
-- Convention : clé de substitution entière (GENERATED BY DEFAULT, pour pouvoir
-- insérer explicitement la ligne 0), identifiant métier conservé en texte à
-- côté. Les trois dimensions qui décrivent une entité (client, produit,
-- vendeur) portent leurs colonnes de validité dès maintenant : l'historisation
-- (SCD2) n'est qu'un algorithme de chargement, aucune migration ne sera à
-- refaire quand il arrivera.
--
-- Pas de colonne jour_ferie dans dim_date : elle viendra d'une migration
-- ultérieure, quand le service référentiel alimentera le chargement.

CREATE SCHEMA IF NOT EXISTS dwh;

-- ---------------------------------------------------------------------------
-- Dimensions
-- ---------------------------------------------------------------------------

-- Un jour calendaire ne change jamais de définition : pas d'historisation.
CREATE TABLE IF NOT EXISTS dwh.dim_date (
    date_id      INTEGER PRIMARY KEY,          -- AAAAMMJJ, ex. 20170315
    date         DATE    NOT NULL UNIQUE,
    annee        INTEGER NOT NULL,
    trimestre    INTEGER NOT NULL,
    mois         INTEGER NOT NULL,
    semaine_iso  INTEGER NOT NULL,
    jour         INTEGER NOT NULL,
    nom_jour     TEXT    NOT NULL,
    nom_mois     TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS dwh.dim_client (
    client_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_unique_id   TEXT    NOT NULL,     -- la personne, jamais customer_id
    ville                TEXT,
    etat                 TEXT,
    code_postal_prefixe  TEXT,
    valide_du            DATE    NOT NULL,
    valide_au            DATE,
    est_courante         BOOLEAN NOT NULL,
    CONSTRAINT ck_dim_client_validite CHECK (est_courante = (valide_au IS NULL))
);

CREATE TABLE IF NOT EXISTS dwh.dim_produit (
    produit_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produit_olist     TEXT    NOT NULL,
    categorie            TEXT,                 -- product_category_name_norm
    categorie_catalogue  TEXT,                 -- depuis la table de correspondance (F1.9)
    id_fiche_rakuten     TEXT,
    rattache             BOOLEAN NOT NULL,
    langue               TEXT,                 -- langue de la fiche rattachée
    valide_du            DATE    NOT NULL,
    valide_au            DATE,
    est_courante         BOOLEAN NOT NULL,
    CONSTRAINT ck_dim_produit_validite CHECK (est_courante = (valide_au IS NULL))
);

CREATE TABLE IF NOT EXISTS dwh.dim_vendeur (
    vendeur_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_vendeur_olist     TEXT    NOT NULL,
    ville                TEXT,
    etat                 TEXT,
    code_postal_prefixe  TEXT,
    valide_du            DATE    NOT NULL,
    valide_au            DATE,
    est_courante         BOOLEAN NOT NULL,
    CONSTRAINT ck_dim_vendeur_validite CHECK (est_courante = (valide_au IS NULL))
);

-- L'index unique partiel garantit qu'il n'existe jamais deux versions
-- courantes à la fois pour le même identifiant métier.
CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_client_courante
    ON dwh.dim_client (customer_unique_id) WHERE est_courante;
CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_produit_courante
    ON dwh.dim_produit (id_produit_olist) WHERE est_courante;
CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_vendeur_courante
    ON dwh.dim_vendeur (id_vendeur_olist) WHERE est_courante;

-- ---------------------------------------------------------------------------
-- Faits
-- ---------------------------------------------------------------------------

-- Une ligne par commande, y compris les commandes sans ligne d'article.
CREATE TABLE IF NOT EXISTS dwh.fait_commande (
    order_id                      TEXT PRIMARY KEY,
    client_id                     INTEGER       NOT NULL,
    date_id                       INTEGER       NOT NULL,   -- date d'achat
    statut                        TEXT          NOT NULL,
    date_achat                    TIMESTAMP,
    date_approbation              TIMESTAMP,
    date_livraison_transporteur   TIMESTAMP,
    date_livraison_client         TIMESTAMP,
    date_livraison_estimee        TIMESTAMP,
    delai_livraison_jours         INTEGER,                  -- NULL si non livrée
    montant_paye                  NUMERIC(12,2) NOT NULL,   -- somme des paiements
    nombre_paiements              INTEGER       NOT NULL,
    a_une_ligne_article           BOOLEAN       NOT NULL,
    CONSTRAINT fk_commande_client FOREIGN KEY (client_id) REFERENCES dwh.dim_client (client_id),
    CONSTRAINT fk_commande_date   FOREIGN KEY (date_id)   REFERENCES dwh.dim_date (date_id),
    -- une commande a toujours un client : la ligne « inconnu » n'est pas permise ici
    CONSTRAINT ck_commande_client_connu CHECK (client_id <> 0)
);

-- Une ligne par article vendu. Olist ne fournit pas de quantité : une ligne,
-- une unité.
CREATE TABLE IF NOT EXISTS dwh.fait_ligne_commande (
    order_id        TEXT          NOT NULL,
    order_item_id   INTEGER       NOT NULL,
    produit_id      INTEGER       NOT NULL,
    vendeur_id      INTEGER       NOT NULL,
    date_id         INTEGER       NOT NULL,   -- date d'achat de la commande parente
    prix            NUMERIC(10,2) NOT NULL,
    frais_port      NUMERIC(10,2) NOT NULL,
    quantite        INTEGER       NOT NULL DEFAULT 1,
    PRIMARY KEY (order_id, order_item_id),
    CONSTRAINT fk_ligne_commande FOREIGN KEY (order_id)   REFERENCES dwh.fait_commande (order_id),
    CONSTRAINT fk_ligne_produit  FOREIGN KEY (produit_id) REFERENCES dwh.dim_produit (produit_id),
    CONSTRAINT fk_ligne_vendeur  FOREIGN KEY (vendeur_id) REFERENCES dwh.dim_vendeur (vendeur_id),
    CONSTRAINT fk_ligne_date     FOREIGN KEY (date_id)    REFERENCES dwh.dim_date (date_id)
);

CREATE INDEX IF NOT EXISTS idx_fait_commande_client ON dwh.fait_commande (client_id);
CREATE INDEX IF NOT EXISTS idx_fait_commande_date   ON dwh.fait_commande (date_id);
CREATE INDEX IF NOT EXISTS idx_fait_ligne_produit   ON dwh.fait_ligne_commande (produit_id);
CREATE INDEX IF NOT EXISTS idx_fait_ligne_vendeur   ON dwh.fait_ligne_commande (vendeur_id);
CREATE INDEX IF NOT EXISTS idx_fait_ligne_date      ON dwh.fait_ligne_commande (date_id);

-- ---------------------------------------------------------------------------
-- La ligne « inconnu » (identifiant 0) de chaque dimension
-- ---------------------------------------------------------------------------
-- Un fait dont la référence manque pointe ici plutôt que d'être perdu. Dans les
-- dimensions historisées, cette ligne est permanente : valide depuis 1900,
-- jamais fermée — ce n'est pas une entité métier qui pourrait changer.

INSERT INTO dwh.dim_date
    (date_id, date, annee, trimestre, mois, semaine_iso, jour, nom_jour, nom_mois)
VALUES (0, '1900-01-01', 0, 0, 0, 0, 0, 'inconnu', 'inconnu')
ON CONFLICT (date_id) DO NOTHING;

INSERT INTO dwh.dim_client
    (client_id, customer_unique_id, ville, etat, code_postal_prefixe,
     valide_du, valide_au, est_courante)
VALUES (0, 'inconnu', 'inconnu', 'inconnu', 'inconnu', '1900-01-01', NULL, TRUE)
ON CONFLICT (client_id) DO NOTHING;

INSERT INTO dwh.dim_produit
    (produit_id, id_produit_olist, categorie, categorie_catalogue, id_fiche_rakuten,
     rattache, langue, valide_du, valide_au, est_courante)
VALUES (0, 'inconnu', 'inconnu', 'inconnu', NULL, FALSE, NULL, '1900-01-01', NULL, TRUE)
ON CONFLICT (produit_id) DO NOTHING;

INSERT INTO dwh.dim_vendeur
    (vendeur_id, id_vendeur_olist, ville, etat, code_postal_prefixe,
     valide_du, valide_au, est_courante)
VALUES (0, 'inconnu', 'inconnu', 'inconnu', 'inconnu', '1900-01-01', NULL, TRUE)
ON CONFLICT (vendeur_id) DO NOTHING;

COMMENT ON SCHEMA dwh IS
    'Entrepot analytique en etoile : faits et dimensions. Voir docs/contrats/entrepot.md.';
